<script>
  import Nav from '~/layout/Nav.svelte'
  import '../app.scss'
</script>

<svelte:head>
  <link rel="icon" type="image/svg" href="/favicon.png">
  <link rel="preconnect" href="https://api.itty.cards" crossorigin>
  <title>SvelteKit Template</title>
  <meta name="description" content="This site was generated by Kevin's SvelteKit Template" />
  <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
  <html lang="en" />
</svelte:head>

<main>
  <Nav version>
    <span slot="brand">
      it<strike>t</strike>y.sh
    </span>

    <a href="https://itty.cards.com">itty.cards</a>
    <a href="https://itty.sh">itty.sh</a>
    <a href="https://aimandkevinbutaimeesnamefirst.com">Another Site</a>
    <a href="https://itty.cards.com">itty.cards</a>
    <a href="https://itty.sh">itty.sh</a>
    <a href="https://aimandkevinbutaimeesnamefirst.com">And Yet Another</a>
    <a href="https://itty.cards.com">itty.cards</a>
  </Nav>

  <section>
    <slot />
  </section>
</main>

<style lang="scss">
  main {
    display: flex;
    flex-flow: column;
    // height: 100%;

    section {
      flex: 1;
      display: flex;
      justify-content: center;
    }
  }
</style>
