<script>
  import Nav from '~/layout/Nav.svelte'
  import Footer from '~/layout/Footer.svelte'
  import '~/styles/app.scss'

  // DEFINES IF THE PAGE IS WIDTH-CONSTRAINED
  let constrained = true
</script>

<svelte:head>
  <link rel="icon" type="image/svg" href="/favicon.png">
  <link rel="preconnect" href="https://api.itty.cards" crossorigin>
  <title>SvelteKit Template</title>
  <meta name="description" content="This site was generated by Kevin's SvelteKit Template" />
  <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
  <html lang="en" />
</svelte:head>

<main class:constrained>
  <Nav version sticky>
    <span slot="brand">
      it<strike>t</strike>y.sh
    </span>

    <a href="/basics">Basics</a>
    <a href="/forms">Forms Elements</a>
    <a href="https://aimandkevinbutaimeesnamefirst.com">Another Site</a>
    <a href="https://itty.cards.com">itty.cards</a>
    <a href="https://itty.sh">itty.sh</a>
    <a href="https://aimandkevinbutaimeesnamefirst.com">And Yet Another</a>
    <a href="https://itty.cards.com">itty.cards</a>
  </Nav>

  <section>
    <slot />
  </section>

  <Footer constrained={constrained} sticky>
    &copy; 2022, All rights reserved.
  </Footer>
</main>

<style lang="scss">
  main {
    display: flex;
    flex-flow: column;

    section {
      flex: 1;
      display: flex;
      justify-content: center;
    }
  }

  small {
    font-size: 0.5em;
    letter-spacing: 0em;
    color: var(--foreground-25);
    top: -0.4rem;
    position: relative;
  }
</style>
